### ISSUE TITLE
Installation of module fails on Strawberry Perl

### ISSUE THREAD

**Issue by srekoc** [ironcamel/Dancer2-Plugin-Email#4]
Strawberry Perl enabled me to develop a full app using Dancer2 on Windiows. Wanted to add a feature to send out an email. In the process tried installing Dancer2::Plugin::Email and it fails with error messages. 

Tried both cpan and cpam with no luck. 

Configuring Dancer2-Plugin-Email-0.0003 ... OK
==> Found dependencies: MIME::Entity
--> Working on MIME::Entity
Fetching http://www.cpan.org/authors/id/D/DS/DSKOLL/MIME-tools-5.507.tar.gz ... OK
Configuring MIME-tools-5.507 ... OK
Building and testing MIME-tools-5.507 ... FAIL
! Installing MIME::Entity failed. See C:\Users\SINDHU~1.cpanm\work\1464293365.16444\build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'MIME::Entity' is not installed
! Bailing out the installation for Dancer2-Plugin-Email-0.0003.

**Comment by ironcamel** [comment]
Looks like the problem is with MIME::Entity

**Comment by SysPete** [comment]
Probably related (MIME::Tools test failure on Windows): https://rt.cpan.org/Public/Bug/Display.html?id=118262

I think this issue should be closed since the bug is in a dependency and appears to be close to being addressed.
