### ISSUE TITLE
subject header is not encoded as quoted-printable

### ISSUE THREAD

**Issue by Happy86** [ironcamel/Dancer2-Plugin-Email#9]
Hi, 

while the body / message is automatically encoded as quoted-printable the subject is not encoded (it seems to be just the string/scalar I hand to the subject key of the anonymous hash).

```
# quote from: https://metacpan.org/pod/Dancer2::Plugin::Email#SYNOPSIS
email {
        from    => 'bob@foo.com',
        to      => 'sue@foo.com',
        subject => 'allo',
        body    => 'Dear Sue, ...',
        attach  => '/path/to/attachment',
    };
```

If I understand [rfc1342](https://tools.ietf.org/html/rfc1342) (and our mail admin who complained that my application **must** only use 7-bit ASCII if one wants to maintain compatibility) the subject and other HEADERS) should also be encoded as quoted-printable to properly work.

I am currently working around this with `MIME::QuotedPrint` and 
`'subject' => '=?utf-8?Q?'.encode_qp($email_subject).'?=',` in my code. However this seems to be somehow inadequate as the RFC states that a header is only allowed to be 75 characters long. 

(The way my code is now it inserts several `=` characters the longer the  subject is.)

Quote from the RFC1342:
> [...] If it is desirable
>   to encode more text than will fit in an encoded-word of 75
>   characters, multiple encoded-words (separated by SPACE or newline)
>   may be used.  Message header lines that contain one or more encoded-
>   words should be no more than 76 characters long.  NOTE: These
>   restrictions are included not only to ease interoperbility through
>   internetwork mail gateways, but also to impose a limit on the amount
>   of lookahead a header parser must employ (while looking for a final
>   ?= delimiter) before it can decide whether a token is an encoded-word
>   or something else. [...]

Best regards, 
Andreas

**Comment by Happy86** [comment]
Sorry. Forgot to mention:
I am using Perl v5.30.0 and Dancer2::Plugin::Email 0.0202 within Perlbrew (tested with CentOS 7 and Ubuntu 18.04).

**Comment by Happy86** [comment]
Ok. Sorry. Seems like I am barking up the wrong tree...

The code 
```
my $subject_string = "[BelWü TTS #3] Ankündigung: Wartungsarbeiten Glasfaser STU-MWK nach HOH-WEST";
my $body = "ich bin ein body ... \näüö";

my $email = MIME::Entity->build
(
    'Charset'   => 'utf-8',
    'Encoding'  => 'quoted-printable',
    'subject'   => $subject_string,
    'Data'      => $body,
);
```
produces the following in the debugger: 
```
  DB<60> x $email->print
Content-Type: text/plain; charset="utf-8"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0
X-Mailer: MIME-tools 5.509 (Entity 5.509)
Subject: [BelWü TTS #3] Ankündigung: Wartungsarbeiten Glasfaser STU-MWK
 nach HOH-WEST

ich bin ein body ...=20
=C3=A4=C3=BC=C3=B6=
0
```
so I'll probably open an issue with `MIME::Entity`. 

Just wanted to document this here before closing the issue if someone else has the same problem. ;-)

**Comment by ironcamel** [comment]
@Happy86 thanks for digging into this.
